services:
  php:
    image: php:8.4-fpm
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - "8000:8000"
    environment:
      - PHP_FPM_LISTEN_ADDRESS=127.0.0.1:8000
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: